### PR TITLE
SQLAbst to allow usage of Transactions

### PR DESCRIPTION
**Pull request by s00500**
As I wanted to build a feature that allows for preview of a modification I needed Transactions to work. I feel like I added the possibility for them in the most minimal invasive way :-)

Simple get the SQLAbst and call Beginx(context.Context) to start one. After a rollback or commit the library will get back to using the db.

Of course this might not be 100% nice in a very concurrent setup but then it makes more sense to just use several clients probably...

### CODE REVIEW

**Comment by s00500** [comment]
(sorry for the merge commit, feel free to squash)

**Comment by dvcrn** [comment]
Sorry I’m unfamiliar with sqlabst, what does it give over https://go.dev/doc/database/execute-transactions?

**Comment by s00500** [comment]
It is a very  simple piece of code basically doing nothing else than bindig together sqlx.DB and sqlx.Tx into a single interface. I would have written this myself if I would not have found that package very fast. If you want we can copy its code into the project to ensure we keep dependencies low and do not run into issues.

**Comment by s00500** [comment]
(My main intention was not to add another version of every function that uses the tx instead but rather build that logic into the client)

**Comment by s00500** [comment]
Thanks!

**Pull request merged**
